spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-phoenix-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-phoenix-test
## please save as UTF-8 format